apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-memory-policy-config.default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
