apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-memory-policy-config.default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
data:
  config.yaml: |
    classes:
    - name: interleave-all
      policy:
        mode: MPOL_INTERLEAVE
        nodes: allowed-mems
    - name: interleave-cpu-packages
      policy:
        mode: MPOL_INTERLEAVE
        nodes: cpu-packages
    - name: interleave-cpu-nodes
      policy:
        mode: MPOL_INTERLEAVE
        nodes: cpu-nodes
    - name: interleave-local-nodes
      policy:
        mode: MPOL_INTERLEAVE
        nodes: max-dist:19
