apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-memtierd-config.default
  namespace: kube-system
data:
  config.yaml: |
    classes:
    - name: swap-idle-data
      allowswap: true
      memtierdconfig: |
        policy:
          name: age
          config: |
            intervalms: 10000
            pidwatcher:
              name: cgroups
              config: |
                cgroups:
                  - $CGROUP2_ABS_PATH
            swapoutms: 10000
            tracker:
              name: idlepage
              config: |
                pagesinregion: 512
                maxcountperregion: 1
                scanintervalms: 10000
            mover:
              intervalms: 20
              bandwidth: 50
