apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nri-memory-qos
  name: nri-memory-qos
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nri-memory-qos
  template:
    metadata:
      labels:
        app: nri-memory-qos
    spec:
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        - name: nri-memory-qos
          command:
            - nri-memory-qos
            - --idx
            - "40"
            - --config
            - /etc/nri/memory-qos/config.yaml
            - -v
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
          - name: memory-qos-config-vol
            mountPath: /etc/nri/memory-qos
          - name: nri-sockets-vol
            mountPath: /var/run/nri
      volumes:
      - name: memory-qos-config-vol
        configMap:
          name: nri-memory-qos-config.default
      - name: nri-sockets-vol
        hostPath:
          path: /var/run/nri
          type: Directory
