apiVersion: config.nri/v1alpha1
kind: BalloonsPolicy
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
policy:
  {{- toYaml .Values.config.policy | nindent 2 }}
common:
  {{- toYaml .Values.config.common | nindent 2 }}
