name: Lint

on:
  push:
    branches:
      - main
      - "release-*"
      - "test/**"
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=10m
